apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - clusters:
        selector:
          matchLabels:
            cloud: aws

  template:
    metadata:
      name: aws-platform
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      source:
        repoURL: https://github.com/micheleformenti/microservices-k8s-platform.git
        targetRevision: main
        path: helm/platform/aws
        helm:
          releaseName: aws-platform
          parameters:
            - name: aws-load-balancer-controller.clusterName
              value: '{{ index .metadata.annotations "gitops-bridge/cluster-name" }}'
            - name: aws-load-balancer-controller.region
              value: '{{ index .metadata.annotations "gitops-bridge/aws-region" }}'
            - name: external-dns.domainFilters[0]
              value: '{{ index .metadata.annotations "gitops-bridge/dns-zone-name" }}'
            - name: external-dns.txtOwnerId
              value: '{{ index .metadata.annotations "gitops-bridge/cluster-name" }}'
            - name: cluster-autoscaler.awsRegion
              value: '{{ index .metadata.annotations "gitops-bridge/aws-region" }}'
            - name: cluster-autoscaler.autoDiscovery.clusterName
              value: '{{ index .metadata.annotations "gitops-bridge/cluster-name" }}'

      destination:
        server: '{{ .server }}'
        namespace: kube-system

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
