apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-workload
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - clusters:
        selector:
          matchLabels:
            cloud: aws

  template:
    metadata:
      name: aws-workload
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      source:
        repoURL: https://github.com/micheleformenti/microservices-k8s-platform.git
        targetRevision: main
        path: helm/application
        helm:
          releaseName: microservices-platform
          valueFiles:
            - values.yaml
            - values-eks.yaml
          parameters:
            - name: externalSecrets.remoteKey
              value: '{{ index .metadata.annotations "gitops-bridge/ghcr-secret-name" }}'
            - name: secretStore.provider.aws.region
              value: '{{ index .metadata.annotations "gitops-bridge/aws-region" }}'
            - name: frontend.ingress.host
              value: '{{ index .metadata.annotations "gitops-bridge/application-domain-name" }}'
            - name: frontend.ingress.annotations.alb\.ingress\.kubernetes\.io/certificate-arn
              value: '{{ index .metadata.annotations "gitops-bridge/application-certificate-arn" }}'

      destination:
        server: '{{ .server }}'
        namespace: microservices-platform

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
