apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ms-k8s-platform.cartServiceLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cartService.replicas }}
  selector:
    matchLabels:
      {{- include "ms-k8s-platform.cartServiceSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ms-k8s-platform.cartServiceSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cartservice
          image: "{{ .Values.cartService.image.repository }}:{{ .Values.cartService.image.tag }}"
          imagePullPolicy: {{ .Values.cartService.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
          resources:
            requests:
              cpu: {{ .Values.cartService.resources.requests.cpu }}
              memory: {{ .Values.cartService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.cartService.resources.limits.cpu }}
              memory: {{ .Values.cartService.resources.limits.memory }}
          readinessProbe:
            initialDelaySeconds: 15
            grpc:
              port: 7070
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            grpc:
              port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ms-k8s-platform.cartServiceLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ms-k8s-platform.cartServiceSelectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
