apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: microservices-platform
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      restartPolicy: Always
      initContainers:
        - command:
          - /bin/sh
          - -exc
          - |
            MAX_RETRIES=12
            RETRY_INTERVAL=10
            for i in $(seq 1 $MAX_RETRIES); do
              echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
              if [ "$STATUSCODE" = "200" ]; then
                  echo "Frontend is reachable."
                  exit 0
              fi
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              sleep $RETRY_INTERVAL
            done
            echo "Failed to reach frontend after $MAX_RETRIES attempts."
            exit 1
          name: frontend-check
          image: busybox:1.37
          imagePullPolicy: IfNotPresent
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
      containers:
        - name: loadgenerator
          image: loadgenerator
          imagePullPolicy: IfNotPresent
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
            - name: USERS
              value: "10"
            - name: RATE
              value: "1"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi