adService:
  image:
    repository: ghcr.io/micheleformenti/adservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
cartService:
  image:
    repository: ghcr.io/micheleformenti/cartservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
checkoutService:
  image:
    repository: ghcr.io/micheleformenti/checkoutservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
currencyService:
  image:
    repository: ghcr.io/micheleformenti/currencyservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
emailService:
  image:
    repository: ghcr.io/micheleformenti/emailservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
frontend:
  image:
    repository: ghcr.io/micheleformenti/frontend
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: alb
    host: eks-demo.aws.micheleformenti.com
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-path: /_healthz
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
  autoscaling:
    enabled: true
loadGenerator:
  image:
    repository: ghcr.io/micheleformenti/loadgenerator
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
paymentService:
  image:
    repository: ghcr.io/micheleformenti/paymentservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
productCatalogService:
  image:
    repository: ghcr.io/micheleformenti/productcatalogservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
recommendationService:
  image:
    repository: ghcr.io/micheleformenti/recommendationservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
redisCart:
  persistence:
    enabled: true
    storageClassName: gp3
    size: 1Gi
shippingService:
  image:
    repository: ghcr.io/micheleformenti/shippingservice
    tag: b524afc85aaaf373f1d2a08633fd1cf09d43f881
    pullPolicy: IfNotPresent
