adService:
  image:
    repository: ghcr.io/micheleformenti/adservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
cartService:
  image:
    repository: ghcr.io/micheleformenti/cartservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
checkoutService:
  image:
    repository: ghcr.io/micheleformenti/checkoutservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
currencyService:
  image:
    repository: ghcr.io/micheleformenti/currencyservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
emailService:
  image:
    repository: ghcr.io/micheleformenti/emailservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
frontend:
  image:
    repository: ghcr.io/micheleformenti/frontend
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
loadGenerator:
  image:
    repository: ghcr.io/micheleformenti/loadgenerator
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
paymentService:
  image:
    repository: ghcr.io/micheleformenti/paymentservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
productCatalogService:
  image:
    repository: ghcr.io/micheleformenti/productcatalogservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
recommendationService:
  image:
    repository: ghcr.io/micheleformenti/recommendationservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
shippingService:
  image:
    repository: ghcr.io/micheleformenti/shippingservice
    tag: 647aa3ff12ef92691fc508487eba51d68d829b29
    pullPolicy: IfNotPresent
