{{- if .Values.frontend.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ms-k8s-platform.frontendLabels" . | nindent 4 }}
spec:
  parentRefs:
    - name: frontend
      sectionName: http
    {{- if .Values.frontend.gateway.tls.enabled }}
    - name: frontend
      sectionName: https
    {{- end }}
  {{- with .Values.frontend.gateway.hostname }}
  hostnames:
    - {{ . | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80
{{- end }}
