apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-productcatalogservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: productcatalogservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: recommendationservice
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: checkoutservice
      ports:
        - protocol: TCP
          port: 3550
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-currencyservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: currencyservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: checkoutservice
      ports:
        - protocol: TCP
          port: 7000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cartservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: cartservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: checkoutservice
      ports:
        - protocol: TCP
          port: 7070
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-recommendationservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: recommendationservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-shippingservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: shippingservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: checkoutservice
      ports:
        - protocol: TCP
          port: 50051
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-checkoutservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: checkoutservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          port: 5050
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-adservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: adservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          port: 9555
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-cart-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: redis-cart
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: cartservice
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-paymentservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: paymentservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: checkoutservice
      ports:
        - protocol: TCP
          port: 50051
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-emailservice-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: emailservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: checkoutservice
      ports:
        - protocol: TCP
          port: 8080
