apiVersion: v2
name: microservices-platform-aws
description: AWS platform resources for the microservices platform
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: aws-load-balancer-controller
    version: 1.14.0
    repository: https://aws.github.io/eks-charts
  - name: external-dns
    version: 1.20.0
    repository: https://kubernetes-sigs.github.io/external-dns/
