storageClasses:
  gp3:
    enabled: true
    name: gp3
    default: false
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    encrypted: true

aws-load-balancer-controller:
  clusterName: microservices-platform-eks
  region: eu-central-1
  serviceAccount:
    create: true
    name: aws-load-balancer-controller

external-dns:
  provider:
    name: aws
  sources:
    - ingress
  domainFilters:
    - aws.micheleformenti.com
  policy: sync
  registry: txt
  txtOwnerId: microservices-platform-eks
  serviceAccount:
    create: true
    name: external-dns
