storageClasses:
  gp3:
    enabled: true
    name: gp3
    default: false
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    encrypted: true

aws-load-balancer-controller:
  serviceAccount:
    create: true
    name: aws-load-balancer-controller

external-dns:
  provider:
    name: aws
  sources:
    - ingress
  domainFilters: []
  policy: sync
  registry: txt
  txtOwnerId: ""
  serviceAccount:
    create: true
    name: external-dns

cluster-autoscaler:
  cloudProvider: aws
  awsRegion: ""
  autoDiscovery:
    clusterName: ""
  image:
    tag: v1.36.1
  rbac:
    serviceAccount:
      create: true
      name: cluster-autoscaler
