apiVersion: v2
name: microservices-platform-azure
description: Azure platform resources for the microservices platform
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: alb-controller
    version: 1.11.4
    repository: oci://mcr.microsoft.com/application-lb/charts
    condition: albController.enabled
  - name: external-dns
    version: 1.20.0
    repository: https://kubernetes-sigs.github.io/external-dns/
    condition: externalDns.enabled
  - name: cert-manager
    version: 1.21.1
    repository: https://charts.jetstack.io
    condition: certManager.enabled
  - name: external-secrets
    version: 2.8.0
    repository: https://charts.external-secrets.io
