# ALB Controller
albController:
  enabled: false

alb-controller:
  albController:
    namespace: aks-platform
    podIdentity:
      clientID: ""

# Application Gateway for Containers
applicationGateway:
  enabled: false
  subnetId: ""

# ExternalDNS
externalDns:
  enabled: false
  azure:
    clientId: ""
    tenantId: ""
    subscriptionId: ""
    resourceGroup: ""

external-dns:
  fullnameOverride: external-dns
  provider:
    name: azure
  sources:
    - gateway-httproute
  domainFilters: []
  policy: sync
  registry: txt
  txtOwnerId: ""
  serviceAccount:
    create: false
    name: external-dns
  podLabels:
    azure.workload.identity/use: "true"
  extraVolumes:
    - name: azure-config
      secret:
        secretName: external-dns-azure
  extraVolumeMounts:
    - name: azure-config
      mountPath: /etc/kubernetes
      readOnly: true

# cert-manager
certManager:
  enabled: false

cert-manager:
  crds:
    enabled: true
  config:
    gatewayAPI:
      enabled: true

# External Secrets Operator
external-secrets:
  fullnameOverride: external-secrets
  podLabels:
    azure.workload.identity/use: "true"
  serviceAccount:
    name: external-secrets
    annotations:
      azure.workload.identity/client-id: ""
