apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-platform-local
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/micheleformenti/microservices-k8s-platform.git
    targetRevision: main
    path: helm/application
    helm:
      releaseName: microservices-platform
      valueFiles:
        - values.yaml
        - values-local.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
