apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/micheleformenti/microservices-k8s-platform.git
    targetRevision: main
    path: helm/observability
    helm:
      releaseName: observability

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
